name: Build and Analyze

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gestor

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

  analyze:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: gestor

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: SonarCloud Scan
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=daniel-agudelo9_automatizacion-calidad \
            -Dsonar.organization=daniel-agudelo99 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.java.binaries=target/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
